### PR TITLE
Same as team_master but with changes to titles of edit and view problems also...

### PR DESCRIPTION
**Pull request by caboteja**
If you guys haven't noticed I implemented viewflipper as to enable the user to swipe through photos without having to be redirected to another screen or have to fill the bottom portion of the screen with photos. Just adjusted the changes because they keep being reverted back to previous states and the variables as well. Just fixed the titles for edit and view for patients and care providers.
 (just pushed to a new branch because even after merging changes and trying to pull again, resulting in git responding 'Already up to date', there were still issues with pushing to team_master as you can see from the multiple times I've tried committing...). Also, i believe it is now up to date with master, just minor changes here and there.

### CODE REVIEW

**Comment by caboteja** [comment]
I took out the other import toolbar because it conflicts with "import android.support.v7.widget.Toolbar;". And I thought I switched and matched the id's from menu_problem_list.xml with the ones from the switch cases or did I forget something?

**Comment by caboteja** [comment]
>           I took out the other import toolbar because it conflicts with "import android.support.v7.widget.Toolbar;". And I thought I switched and matched the id's from menu_problem_list.xml with the ones from the switch cases or did I forget something?

**Comment by caboteja** [comment]
@VinnyLuu I took out the other import toolbar because it conflicts with "import android.support.v7.widget.Toolbar;". And I thought I switched and matched the id's from menu_problem_list.xml with the ones from the switch cases or did I forget something?

**Comment by VinnyLuu** [comment]
oh right. But i dont see the changes you made to the menu_problem_list xml though

**Comment by caboteja** [comment]
@VinnyLuu This is what menu_problem_list.xml currently 
image

**Comment by caboteja** [comment]
@VinnyLuu Yeah I think you're not seeing them because the id's in menu_problem_list.xml I believe were merged into master already, and I believe we have 2 tool bars/task bars now for problem_list view. problem_list_task_bar is the one I recently pushed in.

**Pull request merged**
